apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  annotations:
    secret.reloader.stakater.com/reload: "{{ .Values.service.name }}-secrets"
spec:
  replicas: {{ .Values.service.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
      {{- range $name, $c := .Values.service.deployment.containers }}
        - name: {{ $name }}
          image: {{ $c.image.ref }}
          imagePullPolicy: {{ $c.image.pullPolicy | default "IfNotPresent" }}
          {{- with $.Values.service.env }}
          env:
            {{- range $k, $v := . }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ $.Values.service.name }}-secrets
                optional: true
          {{- with $c.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $c.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $c.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}