apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.service.name }}-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretStoreRef:
    name: notch-secret-store
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: {{ .Values.service.name }}-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: "^notch/{{ .Values.global.env }}/apps/{{ .Values.service.name }}/"
      rewrite:
        - regexp:
            source: ".*/apps/{{ .Values.service.name }}/(.*)"
            target: "$1"